import { BotConfig } from "../types/botConfig";

export const botConfigs: BotConfig[] = [
  {
    id: "cs-bot",
    name: "CS-Bot",
    botToken: process.env.CS_BOT_TOKEN || "",
    signingSecret: process.env.CS_BOT_SIGNING_SECRET || "",
    appToken: process.env.CS_BOT_APP_TOKEN || "",
    role: "system",
    personality: "professional",
    avatar: process.env.CS_BOT_AVATAR || "",
  },
  {
    id: "hanna",
    name: "Hanna",
    botToken: process.env.HANNA_BOT_TOKEN || "",
    signingSecret: process.env.HANNA_BOT_SIGNING_SECRET || "",
    appToken: process.env.HANNA_BOT_APP_TOKEN || "",
    role: "incident_responder",
    personality: "analytical",
    avatar: process.env.HANNA_BOT_AVATAR || "",
  },
  {
    id: "john",
    name: "John",
    botToken: process.env.JOHN_BOT_TOKEN || "",
    signingSecret: process.env.JOHN_BOT_SIGNING_SECRET || "",
    appToken: process.env.JOHN_BOT_APP_TOKEN || "",
    role: "security_analyst",
    personality: "methodical",
    avatar: process.env.JOHN_BOT_AVATAR || "",
  },
  {
    id: "tom",
    name: "Tom",
    botToken: process.env.TOM_BOT_TOKEN || "",
    signingSecret: process.env.TOM_BOT_SIGNING_SECRET || "",
    appToken: process.env.TOM_BOT_APP_TOKEN || "",
    role: "system_admin",
    personality: "technical",
    avatar: process.env.TOM_BOT_AVATAR || "",
  },
  {
    id: "peter",
    name: "Peter",
    botToken: process.env.PETER_BOT_TOKEN || "",
    signingSecret: process.env.PETER_BOT_SIGNING_SECRET || "",
    appToken: process.env.PETER_BOT_APP_TOKEN || "",
    role: "network_engineer",
    personality: "detail-oriented",
    avatar: process.env.PETER_BOT_AVATAR || "",
  },
  {
    id: "mike",
    name: "Mike",
    botToken: process.env.MIKE_BOT_TOKEN || "",
    signingSecret: process.env.MIKE_BOT_SIGNING_SECRET || "",
    appToken: process.env.MIKE_BOT_APP_TOKEN || "",
    role: "security_engineer",
    personality: "proactive",
    avatar: process.env.MIKE_BOT_AVATAR || "",
  },
  {
    id: "lazar",
    name: "Lazar",
    botToken: process.env.LAZAR_BOT_TOKEN || "",
    signingSecret: process.env.LAZAR_BOT_SIGNING_SECRET || "",
    appToken: process.env.LAZAR_BOT_APP_TOKEN || "",
    role: "threat_hunter",
    personality: "investigative",
    avatar: process.env.LAZAR_BOT_AVATAR || "",
  },
];
